// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eimlszeysrpapuwtudij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpbWxzemV5c3JwYXB1d3R1ZGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjUzNjksImV4cCI6MjA2MzAwMTM2OX0.HrHl6vpSVD578UGKBE5WUJHno7cSYsMk8RfVagFdAo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);